services:
  - type: web
    name: valet-parking-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    port: 5000
    autoDeploy: false
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000
